package schedule

import "errors"

var (
	ErrNotFound          = errors.New("scheduled task not found")
	ErrInvalidID         = errors.New("invalid scheduled task id")
	ErrNameRequired      = errors.New("scheduled task name is required")
	ErrPromptRequired    = errors.New("scheduled task prompt is required")
	ErrPromptTooLarge    = errors.New("scheduled task prompt is too large")
	ErrOwnerRequired     = errors.New("scheduled task owner is required")
	ErrInvalidKind       = errors.New("scheduled task kind must be once or cron")
	ErrInvalidTime       = errors.New("scheduled task time must be in the future")
	ErrInvalidCron       = errors.New("invalid five-field cron expression")
	ErrInvalidTimezone   = errors.New("invalid IANA timezone")
	ErrInvalidMaxRuns    = errors.New("max runs cannot be negative")
	ErrInvalidOverlap    = errors.New("invalid overlap policy")
	ErrChatNotFound      = errors.New("scheduled task chat not found")
	ErrProjectRequired   = errors.New("scheduled tasks require a project chat")
	ErrProjectMismatch   = errors.New("scheduled task project does not match its chat")
	ErrAccessDenied      = errors.New("scheduled task access denied")
	ErrOwnerUnregistered = errors.New("scheduled task owner is no longer registered")
	ErrAlreadyExists     = errors.New("scheduled task already exists")
	ErrExecutorBusy      = errors.New("scheduled task chat is busy")
	ErrTaskDisabled      = errors.New("scheduled task is disabled")
	ErrMaxRunsReached    = errors.New("scheduled task has reached its maximum runs")
	ErrIntervalTooSmall  = errors.New("cron schedule fires more often than the minimum interval")
	ErrProjectQuota      = errors.New("project has reached its scheduled task limit")
	ErrArmRequiresUser   = errors.New("arming a scheduled task requires a user")
)
